[package]
name = "rust-deal-or-no-deal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.9.0"
rand = "0.8.4"
colored = "2.0"
prettytable-rs = "0.8.0"
num-format = "0.4"